### PR TITLE
Test excluding Python 3.7 + PyTorch 1.8.1

### PR DESCRIPTION
**Pull request by BenjaminBossan**
For some reason, gpytorch + PyTorch 1.8.1 now caused the following error:

> AttributeError: module 'torch.linalg' has no attribute 'cholesky_ex'

Thus, gpytorch tests are now skipped for that PyTorch version.

Also, no longer exclude 3.9 + 1.5.1, since 1.5.1 is no longer officially
supported and no longer tested.

### CODE REVIEW

File: skorch/tests/test_probabilistic.py [hunk 1]
```diff
@@ -21,8 +21,8 @@
 
 # extract pytorch version without possible '+something' suffix
 pytorch_version, _, _ = torch.__version__.partition('+')
-if LooseVersion(pytorch_version) == '1.7.1':
-    pytest.skip("gpytorch does not work with PyTorch 1.7.1", allow_module_level=True)
+if LooseVersion(pytorch_version) in ('1.7.1', '1.8.1'):
```
Comment (thomasjpfan) [inline skorch/tests/test_probabilistic.py:24]:
```suggestion
# Keep up to date with the gpytorch's supported versions:
# https://github.com/cornellius-gp/gpytorch#installation
if LooseVersion(pytorch_version) >= "1.9":
```

File: .github/workflows/testing.yml [hunk 2]
```diff
@@ -16,11 +16,9 @@ jobs:
     strategy:
       matrix:
         python_version: ['3.6', '3.7', '3.8', '3.9']
-        torch_version: ['1.7.1+cpu', '1.8.1+cpu', '1.9.1+cpu', '1.10.0+cpu']
+        torch_version: ['1.7.1+cpu', '1.8.1+cpu', '1.9.1+cpu', '1.10.1+cpu']
         os: [ubuntu-latest]
         exclude:
-          - python_version: '3.9'
-            torch_version: '1.5.1+cpu'
```
Comment (thomasjpfan) [inline .github/workflows/testing.yml:23]: I think we can remove the following excludes too:

```yaml
          - python_version: '3.9'
             torch_version: '1.6.0+cpu'
```

**Review by thomasjpfan — COMMENTED** [review]
Thanks for the clean up!

**Comment by BenjaminBossan** [comment]
@thomasjpfan Good catch regarding the PyTorch versions officially supported by gpytorch and the obsolete exclusion. I made the adjustments. Please review again.

**Review by thomasjpfan — APPROVED** [review]
LGTM
